<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon Condition="Exists('../../assets/branding/logo.ico')">../../assets/branding/logo.ico</ApplicationIcon>
    <AssemblyName>HashLynx</AssemblyName>
    <RootNamespace>HashLynx.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HashLynx.Core/HashLynx.Core.csproj" />
    <ProjectReference Include="../HashLynx.Hashcat/HashLynx.Hashcat.csproj" />
    <ProjectReference Include="../HashLynx.Extractors/HashLynx.Extractors.csproj" />
    <ProjectReference Include="../HashLynx.Persistence/HashLynx.Persistence.csproj" />
    <Resource Include="../../assets/branding/logo.png" Link="Assets/logo.png" />
    <Resource Include="../../assets/branding/logo_withText.png" Link="Assets/logo_withText.png" />
    <None Include="../../THIRD_PARTY_NOTICES.md" Link="THIRD_PARTY_NOTICES.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
